language: go

go:
  - "1.13"

env:
  global:
    - GOOS=linux

install:
  - ./make.sh

script:
  - cd bin
  - md5sum vxrnet > md5.txt
  - sha256sum vxrnet > sha256.txt
  - sha512sum vxrnet > sha512.txt

deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: PFK8wajMIwCy2d6nK85Qp06yej4iRPLsrdlsFZz0s+2qs3obdvcb3B+9aNDbdw5aSid1oO7ScMIUPQ/d3mdXABQqdQREehIu/vF6qT4D3uh1Fw8n0SQ/9D5Xg//F+0aEGf6ptoJwlaCEbXi7CX97Lnl41BHJkOJAg+b6dVqsbpOPKnPTmwp5owiwlgnDnSCF7gugMNdb+q9yTeDrqPN90L8Qq3E6RPzM//6v9edfcvC9vqaKiPincUagq4T5qLfc3ld+p3VkTXiRKnIC/rl861MT7pIlOkW8l4hglGZOvr2QHOl+PVuMMghkQQgGeWjh1wd0Q8Ps2VqeUDyDqtgamSuqoYNhtg6CS58YDs6LDGrr6FHfpLlSsjXr66IfOiQ7wfKR6U16dJk9uAltxAyprMNzPvff9GsRp7YaQOp3ldDpLNcHaEfLyHA9Jp7mzeNdK/2mEYeWFJgQnI2piBxiPneWtZpu0TKllY5Odo8gUd7Ns4hN63miETgVrBkfJyk1oDoA42zLvH1u2iqzVyuJ/igflgwG8wm1+w85sqyPKdzqBlpLRvtjJP5Uej8vr9AL2uEnhsRnWVUgk9pnR95cfSzdQXP84iAJFDsS4K9jFgKgpeYBrae0yQ5xtqnR9ZSdfHlINBh+RWInZ5FdRAlLW7YFvIXVqu46IEuatvoRRh4=
    file:
      - vxrnet
      - md5.txt
      - sha256.txt
      - sha512.txt
    on:
      tags: true
